### PR TITLE
NUOPC/MOM_restart - read decomposed restarts when PARALLEL_RESTARTFILES

### LINKED ISSUE #22: NUOPC cap fails to handle parallel restart files
When MOM6 is run through the NUOPC driver with `PARALLEL_RESTARTFILES = True`, it successfully writes the per-rank
restart slices (this will be enabled after https://github.com/payu-org/payu/pull/601 gets merged), 

```
access-om3.mom6.r.1900-01-02-00000.nc.0000
access-om3.mom6.r.1900-01-02-00000.nc.0001
...
```

but `rpointer.ocn` contains only the basename, eg, `access-om3.mom6.r.1900-01-02-00000.nc`.

On the next run MOM6/NUOPC cannot locate the restart ensemble and fails with,

```
WARNING: MOM_restart: Unable to find restart file : ...nc.nc
FATAL  : MOM_restart: Unable to find any restart files specified by ...
```

Manual edits of `rpointer.ocn` to enumerate the .nc.000? files avoid the first fatal, but start up then crashes with,

```
NetCDF: Index exceeds dimension bound   (variable: Temp)
```

This is because each slice is opened as a single file, hence each rank thinks the file holds the whole grid and tries to read beyond its local dimenions. 

---

The current fix is to keep the basename in `rpointer.ocn`, but let MOM open it in decomposed mode then each rank can safely read its own piece. I'll wrap it up in a following PR for this fix. 

---
More discussions can be found: https://github.com/ACCESS-NRI/access-om3-configs/issues/592, https://github.com/ACCESS-NRI/access-om3-configs/pull/637, https://github.com/payu-org/payu/pull/601, https://github.com/payu-org/payu/issues/600

### PR DESCRIPTION
**Pull request by minghangli-uni**
closes https://github.com/ACCESS-NRI/MOM6/issues/22

With nuopc driver, this PR adds a branch that when PARALLEL_RESTARTFILES enables, attempts to open decomposed restart files if the single collated file is not found.

### CODE REVIEW

File: src/framework/MOM_restart.F90 [hunk 1]
```diff
@@ -2189,9 +2189,6 @@ function open_restart_units(filename, directory, G, CS, IO_handles, file_paths,
       enddo ! while (still_looking) loop
     else
       filepath = trim(directory)//trim(fname)
-      inquire(file=filepath, exist=fexists)
-      if (.not. fexists) filepath = trim(filepath)//".nc"
```
Comment (dougiesquire) [inline src/framework/MOM_restart.F90]: By removing these lines I think you have modified current behaviour, which could be problematic if we want to get this change upstream.

Do you mind if I push a suggestion? You can always remove it if you don't like it

**Review by dougiesquire — CHANGES_REQUESTED** [review]

File: src/framework/MOM_restart.F90 (hunk 1 above)
Comment (minghangli-uni) [reply src/framework/MOM_restart.F90]: well, this is one of the bugs. With this line `if (.not. fexists) filepath = trim(filepath)//".nc"` in, it will introduce a double .nc suffix error.

Comment (minghangli-uni) [reply src/framework/MOM_restart.F90]: Let me double check and get back to you soon.

Comment (minghangli-uni) [reply src/framework/MOM_restart.F90]: When `parallel_restartfiles` enables and we restart from split files, these lines end up causing crashes

```
inquire(file=filepath, exist=fexists)
if (.not. fexists) filepath = trim(filepath)//'.nc'
```
The reason is that in the split case there is no collated file, suchas `access-om3.mom6.r.1900-01-01-32400.nc` but only slices `.0001, .0002` etc. The first`inquire` hence returns false, and we append another `.nc` turning a correct basename into `…32400.nc.nc`. The subsequent fileset probe then looks for `…nc.nc.0000` and fails:
```
WARNING from PE     0: Unable to find restart file or fileset: ./access-om3.mom6.r.1900-01-01-32400.nc.nc


FATAL from PE     0: MOM_restart: Unable to find any restart files specified by  access-om3.mom6.r.1900-01-01-32400.nc  in directory ./.
```
This does not affect:

- Cold starts - no restart used
- Collated restarts - the single …nc file exists, so the first `inquire` succeeds and we never append

Given that, I removed the “append `.nc`” step in the parallel path so we pass a clean `basename.nc` to the fileset logic.


If we still want them for the historical reason where a missing `.nc` is added automatically, we can keep it but only when not using split restarts. I can make a if condition for it then. But I am not sure if that;s needed.

Comment (dougiesquire) [reply src/framework/MOM_restart.F90]: What you have written [above](https://github.com/ACCESS-NRI/MOM6/pull/23/files#r2272188588) is true for MOM applications that use NUOPC cap with `cesm_coupled=.true.`, as we do. However, there are other ways to set up MOM I think will no longer work with your changes, e.g. if `cesm_coupled=.false.` and the restart filename is provided via `input.nml::MOM_input_nml`.

The change in this PR would be good to include upstream, but to do so we need it to not modify existing behaviour. I'm happy to push a change to fix this, or you can, but I do think it's required before merging.

Comment (minghangli-uni) [reply src/framework/MOM_restart.F90]: Thanks @dougiesquire I pushed https://github.com/ACCESS-NRI/MOM6/pull/23/commits/a1a9cab7011e0cc679c064f88ae1eca223866a18. This should keep the original behaviour.

**Review by dougiesquire — COMMENTED** [review]
Do you mind if I push a suggestion @minghangli-uni? I can't suggest it via the review interface because it affects unchanged lines.

**Comment by minghangli-uni** [comment]
Yeah sure, thanks

**Comment by dougiesquire** [comment]
@minghangli-uni, I've suggested a restructuring in https://github.com/ACCESS-NRI/MOM6/pull/23/commits/86fed55502f17c184981425d9b11978d7f357735. Sorry for being so persnickety with this one - I'm trying to maximise the chance that it gets accepted upstream as is.

Let me know what you think

**Comment by dougiesquire** [comment]
Ooops, added some tabs. Will fix and force push

**Comment by minghangli-uni** [comment]
Thanks @dougiesquire I am happy with this change, it looks great!

**Comment by dougiesquire** [comment]
Have you tested it (I didn't haha)?

**Comment by minghangli-uni** [comment]
Running some local tests now :)

File: src/framework/MOM_restart.F90 [hunk 2]
```diff
@@ -2109,7 +2109,7 @@ function open_restart_units(filename, directory, G, CS, IO_handles, file_paths,
   integer :: nf              ! The number of files that have been found so far
   integer :: m, length
   logical :: still_looking   ! If true, the code is still looking for automatically named files
-  logical :: fexists         ! True if a file has been found
+  logical :: fexists, fexists_parallel ! True if a file has been found
```
Comment (dougiesquire) [inline src/framework/MOM_restart.F90]:
```suggestion
  logical :: fexists, fexists_decomp ! True if a file has been found
```

File: src/framework/MOM_restart.F90 [hunk 3]
```diff
@@ -2190,9 +2190,17 @@ function open_restart_units(filename, directory, G, CS, IO_handles, file_paths,
     else
       filepath = trim(directory)//trim(fname)
       inquire(file=filepath, exist=fexists)
-      if (.not. fexists) filepath = trim(filepath)//".nc"
+      if (.not.fexists .and. CS%parallel_restartfiles) &
+        fexists_parallel = file_exists(filepath, G%Domain)
```
Comment (dougiesquire) [inline src/framework/MOM_restart.F90]:
```suggestion
        fexists_decomp = file_exists(filepath, G%Domain)
```

File: src/framework/MOM_restart.F90 [hunk 4]
```diff
@@ -2190,9 +2190,17 @@ function open_restart_units(filename, directory, G, CS, IO_handles, file_paths,
...
+
+      ! If not found, try with ".nc" extension
+      if (.not.(fexists .or. fexists_parallel)) then
```
Comment (dougiesquire) [inline src/framework/MOM_restart.F90]:
```suggestion
      if (.not.(fexists .or. fexists_decomp)) then
```

File: src/framework/MOM_restart.F90 [hunk 5]
```diff
@@ -2190,9 +2190,17 @@ function open_restart_units(filename, directory, G, CS, IO_handles, file_paths,
...
+        filepath = trim(filepath)//".nc"
+        inquire(file=filepath, exist=fexists)
+        if (.not.fexists .and. CS%parallel_restartfiles) &
+              fexists_parallel = file_exists(filepath, G%Domain)
```
Comment (dougiesquire) [inline src/framework/MOM_restart.F90]:
```suggestion
              fexists_decomp = file_exists(filepath, G%Domain)
```

File: src/framework/MOM_restart.F90 [hunk 6]
```diff
@@ -2202,6 +2210,14 @@ function open_restart_units(filename, directory, G, CS, IO_handles, file_paths,
         if (present(file_paths)) file_paths(nf) = filepath
         if (is_root_pe() .and. (present(IO_handles))) &
           call MOM_error(NOTE,"MOM_restart: MOM run restarted using : "//trim(filepath))
+      elseif (fexists_parallel) then
```
Comment (dougiesquire) [inline src/framework/MOM_restart.F90]:
```suggestion
      elseif (fexists_decomp) then
```

**Review by dougiesquire — COMMENTED** [review]
Rename `fexists_parallel` -> `fexists_decomp`

**Comment by minghangli-uni** [comment]
It runs well from my local tests.

1. starting from scratch with either PARALLEL_RESTARTFILES on or off
2. restarting from collated restart files with either PARALLEL_RESTARTFILES on or off
3. restarting from uncollated restart files with PARALLEL_RESTARTFILES on

**Review by dougiesquire — APPROVED** [review]
Thanks for this @minghangli-uni - we'll definitely want it for our higher res configs

**Comment by minghangli-uni** [comment]
> New changes require approval from someone other than dougiesquire because they were the last pusher.

It seems needing another one to approve this (except me)

**Comment by minghangli-uni** [comment]
@anton-seaice can you help approve it?
